plugins:
  - jest

env:
  node: true
  jest: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  object-curly-newline:
    - error
    - {
        ObjectExpression: { multiline: true, minProperties: 6 },
        ObjectPattern: { multiline: true, minProperties: 6 },
        ImportDeclaration: 'never',
        ExportDeclaration: { multiline: true, minProperties: 6 },
      }
  indent: ["error", 2]
  no-tabs: "error"
  no-use-before-define: ["error", { "functions": false, "variables": false }]
  eol-last: ["error", "always"]
